name: Publish

on:
  push:
    branches:
      - dev
      - ci/01204468838813395_add-release-package
  pull_request:


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: publish
        uses: action-runner/npm-publish@1.6.2
        with:
          tokens: |
            ${{ secrets.NPM_TOKEN }}
            ${{ secrets.TOKEN}}
          packageFiles: |
            package.json
          registries: |
            https://registry.npmjs.org/
            https://npm.pkg.github.com