ame: Publish Package to npmjs
on:
  push:
    branches:
      - dev
      - fix/1205230144231031_npm-package-rebuild
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: [sdk,types]
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: 'nhussain'
      - run: npm ci
      #- run: npm install
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Publish ${{ matrix.packages }}
        working-directory: ./packages/${{ matrix.packages }}
        run: |
           node tools/scripts/publish.mjs @peaq-network/${{ matrix.packages }} next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
